# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

#
# Requiere de guest additions
# vagrant plugin install vagrant-vbguest
#
# Requiere del provider reload
# vagrant plugin install vagrant-reload
#

Vagrant.configure("2") do |config|
  config.vm.define 'oracle' do |oracle|
    oracle.vm.box = "oraclelinux-6-x86_64"
    #oracle.vm.box = "centosPuppet"

    oracle.vm.hostname = "oracle.datum.com.gt"
    #oracle.vm.network 'private_network', type: "dhcp"

    oracle.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
      # Customize the amount of memory on the VM:
      vb.memory = 1024
      vb.cpus = 1
    end
    
    # Instala puppet desde shell para poder ejecutar el siguiente provision
    oracle.vm.provision "shell", inline: <<-SHELL
      echo "Actualizando repositorios"
      yum list >/dev/null 2>&1
      echo "Instalando puppet"
      yum install -y puppet >/dev/null 2>&1
      echo "Instalando plugins de puppet necesarios"
      puppet module install puppetlabs-stdlib
    SHELL

    # Puppet se encarga de la preinstalacion de oracle
    oracle.vm.provision :puppet do |puppet|
      puppet.binary_path = '/usr/bin'
      puppet.manifests_path = 'puppet'
      #puppet.module_path = '/etc/puppet/modules/'
      puppet.manifest_file  = 'preinstall-auto.pp'
      puppet.options        = '--verbose'
    end

    oracle.vm.provision :reload
  end
end
